function [ys_, params, info] = IRFmatch_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(2)=0;
    ys_(1)=0;
    % Auxiliary equations
    check_=0;
end
